### PR TITLE
misspelled amount gangs

### PR DESCRIPTION
**Pull request by Andyauk**
deposit.amount -> deposit.Amount
withdraw.amount -> withdraw.Amount

Describe Pull request
simple misspelling of the key amount

If your PR is to fix an issue mention that issue here

Questions (please complete the following information):

Have you personally loaded this code into an updated qbcore project and checked all it's functionality? yes
Does your code fit the style guidelines? yes
Does your PR fit the contribution guidelines? yes

### CODE REVIEW

**Comment by tom-osborne** [comment]
This PR is actually invalid. See #78 for details.

**Comment by Andyauk** [comment]
> This PR is actually invalid. See #78 for details.

I get that, but these changes I made to gangs is what has already been approved on the [client/cl_boss.lua](https://github.com/qbcore-framework/qb-management/commit/8eddc9eeeb3234e62e8f3d20a0f899ba3f7cc1cb#diff-2cfb5db4f779b88234c9a82010c05c132417a6544f665da5b25a4bb8f69f7065)

So I don't get it. As it was you who made the changes.

**Comment by tom-osborne** [comment]
Yeah that was a mistake to merge that as I mentioned in the issue raised. So those changes will be reverted when the issue is addressed.

**Comment by Andyauk** [comment]
> Yeah that was a mistake to merge that as I mentioned in the issue raised. So those changes will be reverted when the issue is addressed.

It's all good, at times a quick fix is best but I'm glad it's been looked at to find the problem. I'm testing it out now, going to look over sore robbery too, to see if it's like the same issue.

**Pull request closed without merging**
